"""empty message

Revision ID: 49ea0ff5fba5
Revises: 6c09c7cc53fc
Create Date: 2021-02-09 14:18:48.428280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ea0ff5fba5'
down_revision = '6c09c7cc53fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.create_table('revoked_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey')
    )
    # ### end Alembic commands ###
