"""empty message

Revision ID: f2fe566e8ff4
Revises: 
Create Date: 2021-02-15 22:25:12.571961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2fe566e8ff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assigne_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'planneddate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'planneddate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'assigne_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
